- name: Patch and check security settings
  hosts: web
  become: yes
  tasks:

    - name: Check if root filesystem is encrypted with LUKS
      ansible.builtin.command: lsblk -o NAME,MOUNTPOINT,TYPE,FSTYPE
      register: lsblk_out
      changed_when: false

    - name: Display encryption info
      ansible.builtin.debug:
        msg: "{{ lsblk_out.stdout_lines }}"

    - name: Verify SSH is enforcing strong ciphers
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Ciphers'
        line: 'Ciphers aes256-ctr,aes192-ctr,aes128-ctr'
        state: present
      notify: Restart ssh

  handlers:
    - name: Restart ssh
      ansible.builtin.service:
        name: sshd
        state: restarted

